version: '3'
services:
  # ---------------------------
  # api网关
  # ---------------------------
  gateway-service:
    image: docker.io/dockertomuzi/gateway-service:3.2.0-SNAPSHOT
    container_name: gateway-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "8000:8000"
    networks:
      - net

  # ---------------------------
  # 授权服务
  # ---------------------------
  auth-service:
    image: docker.io/dockertomuzi/auth-service:3.2.0-SNAPSHOT
    container_name: auth-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "8090:8090"
    networks:
      - net

  # ---------------------------
  # 用户服务
  # ---------------------------
  user-service:
    image: docker.io/dockertomuzi/user-service:3.2.0-SNAPSHOT
    container_name: user-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "8095:8095"
    networks:
      - net

  # ---------------------------
  # 考试服务
  # ---------------------------
  exam-service:
    image: docker.io/dockertomuzi/exam-service:3.2.0-SNAPSHOT
    container_name: exam-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "8098:8098"
    networks:
      - net

  # ---------------------------
  # 消息服务
  # ---------------------------
  msc-service:
    image: docker.io/dockertomuzi/msc-service:3.2.0-SNAPSHOT
    container_name: msc-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9000:9000"
    networks:
      - net

  # ---------------------------
  # 监控服务
  # ---------------------------
  monitor-service:
    image: docker.io/dockertomuzi/monitor-service:3.2.0-SNAPSHOT
    container_name: monitor-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "8085:8085"
    networks:
      - net

networks:
  net:
    driver: bridge